# Generated by Django 6.0.5 on 2026-05-10 12:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('unit_of_measure', models.CharField(default='units', max_length=50)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'item',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'warehouse',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reserved_qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('source_type', models.CharField(choices=[('SALES_ORDER', 'Sales Order'), ('WORK_ORDER', 'Work Order'), ('PRODUCTION_ORDER', 'Production Order'), ('TRANSFER', 'Internal Transfer'), ('SERVICE_REQUEST', 'Service Request'), ('MANUAL', 'Manual')], max_length=50)),
                ('source_id', models.CharField(help_text='e.g. SO-001, WO-042', max_length=200)),
                ('priority_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('ALLOCATED', 'Allocated'), ('RELEASED', 'Released'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.CharField(default='system', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_priority', models.IntegerField(default=1, help_text='1=Low 2=Medium 3=High 4=VIP')),
                ('delivery_deadline', models.DateTimeField(blank=True, null=True)),
                ('order_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_manufacturing', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'reservation',
                'ordering': ['-priority_score', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovementLedger',
            fields=[
                ('movement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('RECEIPT', 'Stock Receipt'), ('ISSUE', 'Stock Issue'), ('RESERVE', 'Reserve'), ('UNRESERVE', 'Unreserve'), ('ALLOCATE', 'Allocate'), ('ADJUST', 'Manual Adjustment'), ('RETURN', 'Return')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('reference_type', models.CharField(blank=True, max_length=100)),
                ('reference_id', models.CharField(blank=True, max_length=200)),
                ('performed_by', models.CharField(default='system', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'stock_movement_ledger',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReservationEventLog',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('RESERVATION_CREATED', 'Reservation Created'), ('RESERVATION_CONFIRMED', 'Reservation Confirmed'), ('RESERVATION_RELEASED', 'Reservation Released'), ('RESERVATION_EXPIRED', 'Reservation Expired'), ('RESERVATION_CANCELLED', 'Reservation Cancelled'), ('ALLOCATION_TRIGGERED', 'Allocation Triggered'), ('STOCK_RECEIVED', 'Stock Received'), ('ORDER_CANCELLED', 'Order Cancelled'), ('CONFLICT_DETECTED', 'Conflict Detected')], max_length=50)),
                ('triggered_by', models.CharField(default='system', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='inventory.item')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='inventory.reservation')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'reservation_event_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_total', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('quantity_reserved', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('reorder_point', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('version', models.PositiveIntegerField(default=1)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='inventory.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory',
                'unique_together': {('item', 'warehouse')},
            },
        ),
    ]
