# Generated by Django 6.0.5 on 2026-05-10 12:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationRule',
            fields=[
                ('rule_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('strategy', models.CharField(choices=[('FIFO', 'First In First Out'), ('PRIORITY', 'Priority-Based'), ('DEADLINE', 'Deadline-First'), ('PROPORTIONAL', 'Proportional Split'), ('MFG_FIRST', 'Manufacturing First')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher = evaluated first')),
                ('weight_customer_priority', models.FloatField(default=0.4)),
                ('weight_urgency', models.FloatField(default=0.3)),
                ('weight_order_value', models.FloatField(default=0.2)),
                ('weight_aging', models.FloatField(default=0.1)),
                ('condition', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'allocation_rule',
                'ordering': ['-priority'],
            },
        ),
    ]
